/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.misiontic.cesardiaz.vista;

import co.edu.utp.misiontic.cesardiaz.controlador.RestauranteGUIController;
import co.edu.utp.misiontic.cesardiaz.excepcion.ObjetoNoExistenteException;
import co.edu.utp.misiontic.cesardiaz.excepcion.PagoInsuficienteException;
import co.edu.utp.misiontic.cesardiaz.modelo.Adicional;
import co.edu.utp.misiontic.cesardiaz.modelo.Bandeja;
import co.edu.utp.misiontic.cesardiaz.modelo.Carne;
import co.edu.utp.misiontic.cesardiaz.modelo.Completo;
import co.edu.utp.misiontic.cesardiaz.modelo.Ensalada;
import co.edu.utp.misiontic.cesardiaz.modelo.EstadoPedido;
import co.edu.utp.misiontic.cesardiaz.modelo.Jugo;
import co.edu.utp.misiontic.cesardiaz.modelo.Mesa;
import co.edu.utp.misiontic.cesardiaz.modelo.OpcionPedido;
import co.edu.utp.misiontic.cesardiaz.modelo.Pedido;
import co.edu.utp.misiontic.cesardiaz.modelo.Principio;
import co.edu.utp.misiontic.cesardiaz.modelo.Sopa;
import co.edu.utp.misiontic.cesardiaz.vista.modelo.AdicionalModel;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ROG
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private RestauranteGUIController controlador;
    private NumberFormat formatoNumero;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        controlador = new RestauranteGUIController();
        formatoNumero = DecimalFormat.getCurrencyInstance();

        initComponents();
        setSize(800, 600);
        setLocationRelativeTo(null);

        cargarDatos();
        limpiarCampos();
        asignarEstadoCampos(false);
        asignarEstadoCamposMesa(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMesas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPedido = new javax.swing.JList<>();
        btnAgregarPedido = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdCompleto = new javax.swing.JRadioButton();
        rdBandeja = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cmbSopa = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbPrincipio = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbCarne = new javax.swing.JComboBox<>();
        chkEnsalada = new javax.swing.JCheckBox();
        cmbEnsalada = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbJugo = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmbAdicional = new javax.swing.JComboBox<>();
        btnAgregarAdicional = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAdicionales = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtTotalPedido = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtDevuelta = new javax.swing.JTextField();
        spnEfectivo = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTotalMesa = new javax.swing.JTextField();
        btnEntregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restauranete El Corrientazo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mesas");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 130));

        lstMesas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstMesas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMesasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstMesas);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pedidos");

        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 122));

        lstPedido.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPedido.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPedidoValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstPedido);

        btnAgregarPedido.setText("Agregar Pedido");
        btnAgregarPedido.setEnabled(false);
        btnAgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPedidoActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Cliente");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Opción de pedido");

        buttonGroup1.add(rdCompleto);
        rdCompleto.setSelected(true);
        rdCompleto.setText("Completo");
        rdCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCompletoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdBandeja);
        rdBandeja.setText("Bandeja");
        rdBandeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCompletoActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Sopa");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Principio");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Carne");

        chkEnsalada.setSelected(true);
        chkEnsalada.setText("Ensalada");
        chkEnsalada.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        chkEnsalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEnsaladaActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Jugo");

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Adicionales");

        btnAgregarAdicional.setText("Agregar");
        btnAgregarAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAdicionalActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(tblAdicionales);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Total");
        jLabel10.setToolTipText("");

        txtTotalPedido.setEditable(false);
        txtTotalPedido.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtTotalPedido.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCliente)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdCompleto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdBandeja)
                                .addGap(0, 46, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbSopa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkEnsalada, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEnsalada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPrincipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCarne, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbJugo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbAdicional, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarAdicional))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalPedido)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chkEnsalada, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdCompleto)
                    .addComponent(rdBandeja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPrincipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEnsalada)
                    .addComponent(cmbEnsalada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbJugo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarAdicional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Devuelta");

        txtDevuelta.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtDevuelta.setText("0");

        spnEfectivo.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 500));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Efectivo");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Total");

        txtTotalMesa.setEditable(false);
        txtTotalMesa.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtTotalMesa.setText("0");

        btnEntregar.setText("Entregar");
        btnEntregar.setEnabled(false);
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDevuelta)
                            .addComponent(spnEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addComponent(btnPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalMesa)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEntregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtTotalMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spnEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPagar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarPedido)
                            .addComponent(jLabel12)
                            .addComponent(txtDevuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEntregar)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gestion de Pedidos", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tablas maestras", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkEnsaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEnsaladaActionPerformed
        if (!chkEnsalada.isSelected()) {
            cmbEnsalada.setEnabled(false);
            cmbEnsalada.setSelectedIndex(-1);
        } else {
            cmbEnsalada.setEnabled(true);
        }
    }//GEN-LAST:event_chkEnsaladaActionPerformed

    private void rdCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCompletoActionPerformed
        if (rdCompleto.isSelected()) {
            cmbSopa.setEnabled(true);
        } else {
            cmbSopa.setEnabled(false);
            cmbSopa.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_rdCompletoActionPerformed

    private void lstMesasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMesasValueChanged
        var mesa = lstMesas.getSelectedValue();
        lstPedido.removeAll();
        if (mesa != null) {
            asignarEstadoCamposMesa(true);
            try {
                // Cargar los pedidos
                var pedidos = controlador.listarPedidosDeMesa(mesa);
                var model = new DefaultListModel<Pedido>();
                model.addAll(pedidos);
                lstPedido.setModel(model);

                // Actualiza el total de la mesa
                var total = controlador.calcularTotalMesa(mesa);
                limpiarCamposMesa();
                txtTotalMesa.setText(formatoNumero.format(total));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error trabajando con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ObjetoNoExistenteException ex) {
                JOptionPane.showMessageDialog(this, "No hay pedidos para esta mesa", "Error", JOptionPane.WARNING_MESSAGE);
            }
            btnAgregarPedido.setEnabled(true);
        } else {
            asignarEstadoCamposMesa(false);
            limpiarCamposMesa();
            btnAgregarPedido.setEnabled(false);
            txtTotalMesa.setText("0");
        }
    }//GEN-LAST:event_lstMesasValueChanged

    private void lstPedidoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPedidoValueChanged
        var pedido = lstPedido.getSelectedValue();
        if (pedido != null) {
            asignarEstadoCampos(true);
            txtCliente.setText(pedido.getCliente());
            btnEntregar.setEnabled(pedido.getEstado() == EstadoPedido.PENDIENTE_ENTREGA);

            if (pedido.getOpcion() instanceof Completo) {
                var completo = (Completo) pedido.getOpcion();
                rdCompleto.setSelected(true);

                cmbSopa.setSelectedItem(completo.getSopa());
            } else {
                rdBandeja.setSelected(true);
            }
            rdCompletoActionPerformed(null);

            cmbPrincipio.setSelectedItem(pedido.getOpcion().getPrincipio());

            cmbCarne.setSelectedItem(pedido.getOpcion().getCarne());

            if (pedido.getOpcion().getEnsalada() != null) {
                chkEnsalada.setSelected(true);
                cmbEnsalada.setSelectedItem(pedido.getOpcion().getEnsalada());
            } else {
                chkEnsalada.setSelected(false);
            }
            chkEnsaladaActionPerformed(null);

            cmbJugo.setSelectedItem(pedido.getOpcion().getJugo());

            var adicionales = new ArrayList<Adicional>();
            adicionales.addAll(pedido.getAdicionales());
            tblAdicionales.setModel(new AdicionalModel(adicionales));

            // calcular total
            txtTotalPedido.setText(formatoNumero.format(pedido.calcularValor()));
        } else {
            btnEntregar.setEnabled(false);
            limpiarCampos();
            asignarEstadoCampos(false);
        }
    }//GEN-LAST:event_lstPedidoValueChanged

    private void btnAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPedidoActionPerformed
        lstPedido.clearSelection();
        asignarEstadoCampos(true);
        txtCliente.requestFocus();
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnAgregarPedidoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO Validar campos

        // Carga el pedido
        OpcionPedido opcion = null;
        if (rdCompleto.isSelected()) {
            opcion = new Completo(12_000);

            ((Completo) opcion).setSopa((Sopa) cmbSopa.getSelectedItem());
        } else {
            opcion = new Bandeja(10_000);
        }
        opcion.setPrincipio((Principio) cmbPrincipio.getSelectedItem());
        opcion.setCarne((Carne) cmbCarne.getSelectedItem());
        if (chkEnsalada.isSelected()) {
            opcion.setEnsalada((Ensalada) cmbEnsalada.getSelectedItem());
        }
        opcion.setJugo((Jugo) cmbJugo.getSelectedItem());

        var pedido = new Pedido(txtCliente.getText().trim(), opcion);
        pedido.setMesa(lstMesas.getSelectedValue());

        try {
            // Envia a guardar a la base de datos
            controlador.guardarPedido(pedido);

            txtTotalPedido.setText(formatoNumero.format(pedido.calcularValor()));

            // Actualiza la lista de pedidos de la mesa seleccionada
            lstMesasValueChanged(null);

            asignarEstadoCampos(false);
            limpiarCampos();
            btnGuardar.setEnabled(false);

            JOptionPane.showMessageDialog(this, "Pedido guardado de manera exitosa");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error trabajando con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAdicionalActionPerformed
        // Validar campo
        if (cmbAdicional.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto adicional", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Envio a guardar el adicional
            var pedido = lstPedido.getSelectedValue();
            var adicional = (Adicional) cmbAdicional.getSelectedItem();
            controlador.agregarAdicionalPedido(pedido, adicional);

            // Agregar el adicional a la tabla visual
            ((AdicionalModel) tblAdicionales.getModel()).addRow(adicional);
            pedido.agregarAdicional(adicional);

            // Limpar el adicional
            cmbAdicional.setSelectedIndex(-1);

            txtTotalPedido.setText(formatoNumero.format(pedido.calcularValor()));

            JOptionPane.showMessageDialog(this, "Adicional agregado de manera exitosa");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error trabajando con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnAgregarAdicionalActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        try {
            var mesa = lstMesas.getSelectedValue();
            var efectivo = (Integer) spnEfectivo.getValue();

            var devuelta = controlador.pagarCuenta(mesa, efectivo);
            txtDevuelta.setText(formatoNumero.format(devuelta));

            JOptionPane.showMessageDialog(this, "La cuenta se ha pagado correctamente");
            
            lstMesasValueChanged(null);

        } catch (PagoInsuficienteException | ObjetoNoExistenteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error trabajando con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        try {
            var pedido = lstPedido.getSelectedValue();
            controlador.entregarPedido(pedido);

            JOptionPane.showMessageDialog(this, "El pedido ha sido entregado");
            
            lstMesasValueChanged(null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error trabajando con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEntregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAdicional;
    private javax.swing.JButton btnAgregarPedido;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPagar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkEnsalada;
    private javax.swing.JComboBox<Adicional> cmbAdicional;
    private javax.swing.JComboBox<Carne> cmbCarne;
    private javax.swing.JComboBox<Ensalada> cmbEnsalada;
    private javax.swing.JComboBox<Jugo> cmbJugo;
    private javax.swing.JComboBox<Principio> cmbPrincipio;
    private javax.swing.JComboBox<Sopa> cmbSopa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<Mesa> lstMesas;
    private javax.swing.JList<Pedido> lstPedido;
    private javax.swing.JRadioButton rdBandeja;
    private javax.swing.JRadioButton rdCompleto;
    private javax.swing.JSpinner spnEfectivo;
    private javax.swing.JTable tblAdicionales;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDevuelta;
    private javax.swing.JTextField txtTotalMesa;
    private javax.swing.JTextField txtTotalPedido;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        try {
            // Cargar la lista de Mesas
            var mesas = controlador.listarMesas();
            lstMesas.removeAll();
            var model = new DefaultListModel<Mesa>();
            model.addAll(mesas);
            lstMesas.setModel(model);

            // Cargar opciones de Sopa
            cmbSopa.removeAllItems();
            controlador.listarSopas()
                    .forEach(cmbSopa::addItem);

            cmbPrincipio.removeAllItems();
            controlador.listarPrincipios()
                    .forEach(cmbPrincipio::addItem);

            cmbCarne.removeAllItems();
            controlador.listarCarnes()
                    .forEach(cmbCarne::addItem);

            cmbEnsalada.removeAllItems();
            controlador.listarEnsaladas()
                    .forEach(cmbEnsalada::addItem);

            cmbJugo.removeAllItems();
            controlador.listarJugos()
                    .forEach(cmbJugo::addItem);

            cmbAdicional.removeAllItems();
            controlador.listarAdicionales()
                    .forEach(cmbAdicional::addItem);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error trabajando con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void asignarEstadoCampos(boolean habilitado) {
        txtCliente.setEditable(habilitado);
        rdCompleto.setEnabled(habilitado);
        rdBandeja.setEnabled(habilitado);
        cmbSopa.setEnabled(habilitado);
        cmbPrincipio.setEnabled(habilitado);
        cmbCarne.setEnabled(habilitado);
        chkEnsalada.setEnabled(habilitado);
        cmbEnsalada.setEnabled(habilitado);
        cmbJugo.setEnabled(habilitado);
        cmbAdicional.setEnabled(habilitado);
        btnAgregarAdicional.setEnabled(habilitado);

        txtTotalPedido.setEnabled(habilitado);
    }

    private void asignarEstadoCamposMesa(boolean habilitado) {
        txtTotalMesa.setEnabled(habilitado);
        spnEfectivo.setEnabled(habilitado);
        btnPagar.setEnabled(habilitado);
        txtDevuelta.setEnabled(habilitado);
    }

    private void limpiarCampos() {
        txtCliente.setText("");
        cmbSopa.setSelectedIndex(-1);
        cmbPrincipio.setSelectedIndex(-1);
        cmbCarne.setSelectedIndex(-1);
        chkEnsalada.setSelected(true);
        cmbEnsalada.setSelectedIndex(-1);
        cmbJugo.setSelectedIndex(-1);
        cmbAdicional.setSelectedIndex(-1);

        // Limpiar tabla adicionales
        tblAdicionales.setModel(new AdicionalModel(new ArrayList<>()));

        txtTotalPedido.setText("0");
    }

    private void limpiarCamposMesa() {
        txtTotalMesa.setText("0");
        spnEfectivo.setValue(0);
        txtDevuelta.setText("0");
    }
}
